level_0 = {
    'arbustos casa1': "./niveis/level_0/level_0_arbustos casa1.csv",
    'arbustos cena2': "./niveis/level_0/level_0_arbustos cena 2.csv",
    'arvore2': "./niveis/level_0/level_0_arvore2.csv",
    'arvores': "./niveis/level_0/level_0_arvores.csv",
    'arvores cena 3': "./niveis/level_0/level_0_arvores cena 3.csv",
    'buraco da janela': "./niveis/level_0/level_0_buraco da janela.csv",
    'buraco das janelas': "./niveis/level_0/level_0_buraco das janelas.csv",
    'casa roxa': "./niveis/level_0/level_0_casa roxa.csv",
    'casa1': "./niveis/level_0/level_0_casa1.csv",
    'casa2 frente': "./niveis/level_0/level_0_casa2 frente.csv",
    'ceu': "./niveis/level_0/level_0_ceu.csv",
    'chamines': "./niveis/level_0/level_0_chamines.csv",
    'chao': "./niveis/level_0/level_0_chao.csv",
    'chao cena 3': "./niveis/level_0/level_0_chao cena 3.csv",
    'decoracao': "./niveis/level_0/level_0_decoracao.csv",
    'enfeites da cena 2': "./niveis/level_0/level_0_enfeites da cena 2.csv",
    'enfeites dos telhados': "./niveis/level_0/level_0_enfeites dos telhados.csv",
    'enfeites finais da cena2': "./niveis/level_0/level_0_enfeites finais da cena 2.csv",
    'escada casa1': "./niveis/level_0/level_0_escada casa1.csv",
    'escada cena': "./niveis/level_0/level_0_escada cena.csv",
    'escada cena 3': "./niveis/level_0/level_0_escada cena 3.csv",
    'escada morro': "./niveis/level_0/level_0_escada morro.csv",
    'estrelas e luas': "./niveis/level_0/level_0_estrelas e luas.csv",
    'fundo casa2': "./niveis/level_0/level_0_fundo casa2.csv",
    'fundo pizzaria': "./niveis/level_0/level_0_fundo pizzaria.csv",
    'grama': "./niveis/level_0/level_0_grama.csv",
    'hotel': "./niveis/level_0/level_0_hotel.csv",
    'jardim da casa1': "./niveis/level_0/level_0_jardim da casa1.csv",
    'loja cena2': "./niveis/level_0/level_0_loja cena2.csv",
    'mato cena 3': "./niveis/level_0/level_0_mato cena 3.csv",
    'mato cena 2': "./niveis/level_0/level_0_mato cena2.csv",
    'mato complementar': "./niveis/level_0/level_0_mato complementar.csv",
    'mato complementar 2': "./niveis/level_0/level_0_mato complementar 2.csv",
    'mato do predio verde': "./niveis/level_0/level_0_mato do predio verde.csv",
    'morro cena2': "./niveis/level_0/level_0_morro cena2.csv",
    'nuvens': "./niveis/level_0/level_0_nuvens.csv",
    'parede preta': "./niveis/level_0/level_0_parede preta.csv",
    'parte da frente da escada': "./niveis/level_0/level_0_parte da frente da escada.csv",
    'pizzaria': "./niveis/level_0/level_0_pizzaria.csv",
    'placa de bem vindo': "./niveis/level_0/level_0_placa de bem vindo.csv",
    'plataformas': "./niveis/level_0/level_0_plataformas.csv",
    'ponte': "./niveis/level_0/level_0_ponte.csv",
    'portas e janelas': "./niveis/level_0/level_0_portas e janelas.csv",
    'predio azul': "./niveis/level_0/level_0_predio azul.csv",
    'predio marron': "./niveis/level_0/level_0_predio marron.csv",
    'predio rosa': "./niveis/level_0/level_0_predio rosa.csv",
    'predio verde': "./niveis/level_0/level_0_predio verde.csv",
    'predio vermelho': "./niveis/level_0/level_0_predio vermelho.csv",
    'predios': "./niveis/level_0/level_0_predios.csv",
    'props cena 3': "./niveis/level_0/level_0_props cena 3.csv",
    'sacadas': "./niveis/level_0/level_0_sacadas.csv",
    'tapumes e cercas': "./niveis/level_0/level_0_tapumes e cercas.csv",
    'telhado fundos': "./niveis/level_0/level_0_telhado fundos.csv",
    'telhado predio marron': "./niveis/level_0/level_0_telhado predio marron.csv",
    'telhado predio vermelho': "./niveis/level_0/level_0_telhado predio vermelho.csv",
    'telhados': "./niveis/level_0/level_0_telhados.csv",
    'inimigos': './niveis/level_0/level_0_inimigos.csv',
    'constraints': './niveis/level_0/level_0_inimigos.csv',
}
