king = {
    'arbustos_casa1': "../niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "../niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "../niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "../niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "../niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "../niveis/level_0/level_0_casa_1.csv",
    'cercas': "../niveis/level_0/level_0_cercas.csv",
    'ceu': "../niveis/level_0/level_0_ceu.csv",
    'chao': "../niveis/level_0/level_0_chao.csv",
    'grades_casa2': "../niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "../niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "../niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "../niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "../niveis/level_0/level_0_portas_janelas.csv",
    'predios': "../niveis/level_0/level_0_predios.csv",
    'tapumes': "../niveis/level_0/level_0_tapumes.csv",
    'telhados': "../niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "../niveis/level_0/level_0_telhados_fundos.csv",
    'player': "../niveis/level_0/level_0_player.csv",
    'escada': "../niveis/level_0/level_0_escada.csv",
    'sombras': "../niveis/level_0/level_0_sombras.csv",
    'casa_3':"../niveis/level_0/level_0_casa_3.csv",
    'extra_casa3': "../niveis/level_0/level_0_extra_casa3.csv",
    'jardim_casa3': "../niveis/level_0/level_0_jardim_casa3.csv",
    'grades_cima': "../niveis/level_0/level_0_grades_cima.csv",
    'grades_extra': "../niveis/level_0/level_0_grades_extra.csv",
    'extra_predio4': "../niveis/level_0/level_0_extra_predio4.csv",
    'predio_4': "../niveis/level_0/level_0_predio_4.csv",
    'subsolo_emcima': "../niveis/level_0/level_0_subsolo_emcima.csv",
    'subsolo': "../niveis/level_0/level_0_subsolo.csv",
    'parede_subsolo': "../niveis/level_0/level_0_parede_subsolo.csv",
    'estrelas': "../niveis/level_0/level_0_estrelas.csv",
    'hotel': "../niveis/level_0/level_0_hotel.csv",
    'predio_alto': "../niveis/level_0/level_0_predio_alto.csv",
    'ponte': "../niveis/level_0/level_0_ponte.csv",
    'constraints': "../niveis/level_0/level_0_constraints.csv",
    'enemies': "../niveis/level_0/level_0_enemies.csv",
    'colher': "../niveis/level_0/level_0_colher.csv",
    'pergaminho': "../niveis/level_0/level_0_pergaminho.csv",
    'colar': "../niveis/level_0/level_0_colar.csv",
    'perfume': "../niveis/level_0/level_0_perfume.csv",
    'capuz': "../niveis/level_0/level_0_capuz.csv",
    'anel': "../niveis/level_0/level_0_anel.csv",
    'chave': "../niveis/level_0/level_0_chave.csv",
    'node_pos': (160, 400),
    'unlock': 1,
    'node_graphics': "../img/selection/0",
    'death_pos': (650, 336),
    'death_graphics': "../img/death/0/",
}
knight = {
    'arbustos_casa1': "../niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "../niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "../niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "../niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "../niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "../niveis/level_0/level_0_casa_1.csv",
    'cercas': "../niveis/level_0/level_0_cercas.csv",
    'ceu': "../niveis/level_0/level_0_ceu.csv",
    'chao': "../niveis/level_0/level_0_chao.csv",
    'grades_casa2': "../niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "../niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "../niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "../niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "../niveis/level_0/level_0_portas_janelas.csv",
    'predios': "../niveis/level_0/level_0_predios.csv",
    'tapumes': "../niveis/level_0/level_0_tapumes.csv",
    'telhados': "../niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "../niveis/level_0/level_0_telhados_fundos.csv",
    'player': "../niveis/level_0/level_0_player.csv",
    'escada': "../niveis/level_0/level_0_escada.csv",
    'sombras': "../niveis/level_0/level_0_sombras.csv",
    'casa_3':"../niveis/level_0/level_0_casa_3.csv",
    'extra_casa3': "../niveis/level_0/level_0_extra_casa3.csv",
    'jardim_casa3': "../niveis/level_0/level_0_jardim_casa3.csv",
    'grades_cima': "../niveis/level_0/level_0_grades_cima.csv",
    'grades_extra': "../niveis/level_0/level_0_grades_extra.csv",
    'extra_predio4': "../niveis/level_0/level_0_extra_predio4.csv",
    'predio_4': "../niveis/level_0/level_0_predio_4.csv",
    'subsolo_emcima': "../niveis/level_0/level_0_subsolo_emcima.csv",
    'subsolo': "../niveis/level_0/level_0_subsolo.csv",
    'parede_subsolo': "../niveis/level_0/level_0_parede_subsolo.csv",
    'estrelas': "../niveis/level_0/level_0_estrelas.csv",
    'hotel': "../niveis/level_0/level_0_hotel.csv",
    'predio_alto': "../niveis/level_0/level_0_predio_alto.csv",
    'ponte': "../niveis/level_0/level_0_ponte.csv",
    'constraints': "../niveis/level_0/level_0_constraints.csv",
    'enemies': "../niveis/level_0/level_0_enemies.csv",
    'colher': "../niveis/level_0/level_0_colher.csv",
    'pergaminho': "../niveis/level_0/level_0_pergaminho.csv",
    'colar': "../niveis/level_0/level_0_colar.csv",
    'perfume': "../niveis/level_0/level_0_perfume.csv",
    'capuz': "../niveis/level_0/level_0_capuz.csv",
    'anel': "../niveis/level_0/level_0_anel.csv",
    'chave': "../niveis/level_0/level_0_chave.csv",
    'node_pos': (485, 400),
    'unlock': 2,
    'node_graphics': "../img/selection/1",
    'death_pos': (650, 336),
    'death_graphics': "../img/death/1/",
}
meowolas = {
    'arbustos_casa1': "../niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "../niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "../niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "../niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "../niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "../niveis/level_0/level_0_casa_1.csv",
    'cercas': "../niveis/level_0/level_0_cercas.csv",
    'ceu': "../niveis/level_0/level_0_ceu.csv",
    'chao': "../niveis/level_0/level_0_chao.csv",
    'grades_casa2': "../niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "../niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "../niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "../niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "../niveis/level_0/level_0_portas_janelas.csv",
    'predios': "../niveis/level_0/level_0_predios.csv",
    'tapumes': "../niveis/level_0/level_0_tapumes.csv",
    'telhados': "../niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "../niveis/level_0/level_0_telhados_fundos.csv",
    'escada': "../niveis/level_0/level_0_escada.csv",
    'sombras': "../niveis/level_0/level_0_sombras.csv",
    'casa_3': "../niveis/level_0/level_0_casa_3.csv",
    'extra_casa3': "../niveis/level_0/level_0_extra_casa3.csv",
    'jardim_casa3': "../niveis/level_0/level_0_jardim_casa3.csv",
    'grades_cima': "../niveis/level_0/level_0_grades_cima.csv",
    'grades_extra': "../niveis/level_0/level_0_grades_extra.csv",
    'extra_predio4': "../niveis/level_0/level_0_extra_predio4.csv",
    'predio_4': "../niveis/level_0/level_0_predio_4.csv",
    'subsolo_emcima': "../niveis/level_0/level_0_subsolo_emcima.csv",
    'subsolo': "../niveis/level_0/level_0_subsolo.csv",
    'parede_subsolo': "../niveis/level_0/level_0_parede_subsolo.csv",
    'estrelas': "../niveis/level_0/level_0_estrelas.csv",
    'hotel': "../niveis/level_0/level_0_hotel.csv",
    'predio_alto': "../niveis/level_0/level_0_predio_alto.csv",
    'ponte': "../niveis/level_0/level_0_ponte.csv",
    'player': "../niveis/level_0/level_0_player.csv",
    'constraints': "../niveis/level_0/level_0_constraints.csv",
    'enemies': "../niveis/level_0/level_0_enemies.csv",
    'colher': "../niveis/level_0/level_0_colher.csv",
    'pergaminho': "../niveis/level_0/level_0_pergaminho.csv",
    'colar': "../niveis/level_0/level_0_colar.csv",
    'perfume': "../niveis/level_0/level_0_perfume.csv",
    'capuz': "../niveis/level_0/level_0_capuz.csv",
    'anel': "../niveis/level_0/level_0_anel.csv",
    'chave': "../niveis/level_0/level_0_chave.csv",
    'node_pos': (810, 400),
    'unlock': 3,
    'node_graphics': "../img/selection/2",
    'death_pos': (650, 336),
    'death_graphics': "../img/death/2/",
}
mage = {
    'arbustos_casa1': "../niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "../niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "../niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "../niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "../niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "../niveis/level_0/level_0_casa_1.csv",
    'cercas': "../niveis/level_0/level_0_cercas.csv",
    'ceu': "../niveis/level_0/level_0_ceu.csv",
    'chao': "../niveis/level_0/level_0_chao.csv",
    'grades_casa2': "../niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "../niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "../niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "../niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "../niveis/level_0/level_0_portas_janelas.csv",
    'predios': "../niveis/level_0/level_0_predios.csv",
    'tapumes': "../niveis/level_0/level_0_tapumes.csv",
    'telhados': "../niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "../niveis/level_0/level_0_telhados_fundos.csv",
    'player': "../niveis/level_0/level_0_player.csv",
    'escada': "../niveis/level_0/level_0_escada.csv",
    'sombras': "../niveis/level_0/level_0_sombras.csv",
    'casa_3':"../niveis/level_0/level_0_casa_3.csv",
    'extra_casa3': "../niveis/level_0/level_0_extra_casa3.csv",
    'jardim_casa3': "../niveis/level_0/level_0_jardim_casa3.csv",
    'grades_cima': "../niveis/level_0/level_0_grades_cima.csv",
    'grades_extra': "../niveis/level_0/level_0_grades_extra.csv",
    'extra_predio4': "../niveis/level_0/level_0_extra_predio4.csv",
    'predio_4': "../niveis/level_0/level_0_predio_4.csv",
    'subsolo_emcima': "../niveis/level_0/level_0_subsolo_emcima.csv",
    'subsolo': "../niveis/level_0/level_0_subsolo.csv",
    'parede_subsolo': "../niveis/level_0/level_0_parede_subsolo.csv",
    'estrelas': "../niveis/level_0/level_0_estrelas.csv",
    'hotel': "../niveis/level_0/level_0_hotel.csv",
    'predio_alto': "../niveis/level_0/level_0_predio_alto.csv",
    'ponte': "../niveis/level_0/level_0_ponte.csv",
    'constraints': "../niveis/level_0/level_0_constraints.csv",
    'enemies': "../niveis/level_0/level_0_enemies.csv",
    'colher': "../niveis/level_0/level_0_colher.csv",
    'pergaminho': "../niveis/level_0/level_0_pergaminho.csv",
    'colar': "../niveis/level_0/level_0_colar.csv",
    'perfume': "../niveis/level_0/level_0_perfume.csv",
    'capuz': "../niveis/level_0/level_0_capuz.csv",
    'anel': "../niveis/level_0/level_0_anel.csv",
    'chave': "../niveis/level_0/level_0_chave.csv",
    'node_pos': (1135, 400),
    'unlock': 4,
    'node_graphics': "../img/selection/3",
    'death_pos': (650, 336),
    'death_graphics': "../img/death/3/",
}


characters = {
    0: king,
    1: knight,
    2: meowolas,
    3: mage,
}