king = {
    'arbustos_casa1': "./niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "./niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "./niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "./niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "./niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "./niveis/level_0/level_0_casa_1.csv",
    'cercas': "./niveis/level_0/level_0_cercas.csv",
    'ceu': "./niveis/level_0/level_0_ceu.csv",
    'chao': "./niveis/level_0/level_0_chao.csv",
    'grades_casa2': "./niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "./niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "./niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "./niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "./niveis/level_0/level_0_portas_janelas.csv",
    'predios': "./niveis/level_0/level_0_predios.csv",
    'tapumes': "./niveis/level_0/level_0_tapumes.csv",
    'telhados': "./niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "./niveis/level_0/level_0_telhados_fundos.csv",
    'player': "./niveis/level_0/level_0_player.csv",
    'transicao': "./niveis/level_0/level_0_transicao.csv",
    'parede_preta': "./niveis/level_0/level_0_cena2_parede_preta.csv",
    'predio_rosa': "./niveis/level_0/level_0_cena2_predio_rosa.csv",
    'predio_azul': "./niveis/level_0/level_0_cena2_predio_azul.csv",
    'chao_cena2': "./niveis/level_0/level_0_cena2_chao_cena2.csv",
    'predio_verde': "./niveis/level_0/level_0_cena2_predio_verde.csv",
    'predio_marron': "./niveis/level_0/level_0_cena2_predio_marron.csv",
    'predio_vermelho': "./niveis/level_0/level_0_cena2_predio_vermelho.csv",
    'vegetacao': "./niveis/level_0/level_0_cena2_vegetacao.csv",
    'portas_janelas_cena2': "./niveis/level_0/level_0_cena2_portas_janelas_cena2.csv",
    'props_cena2': "./niveis/level_0/level_0_cena2_props_cena2.csv",
    'constraints': "./niveis/level_0/level_0_constraints.csv",
    'enemies': "./niveis/level_0/level_0_enemies.csv",
    'node_pos': (225, 500),
    'unlock': 1,
    'node_graphics': "./img/selection/0",
}
knight = {
    'arbustos_casa1': "./niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "./niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "./niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "./niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "./niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "./niveis/level_0/level_0_casa_1.csv",
    'cercas': "./niveis/level_0/level_0_cercas.csv",
    'ceu': "./niveis/level_0/level_0_ceu.csv",
    'chao': "./niveis/level_0/level_0_chao.csv",
    'grades_casa2': "./niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "./niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "./niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "./niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "./niveis/level_0/level_0_portas_janelas.csv",
    'predios': "./niveis/level_0/level_0_predios.csv",
    'tapumes': "./niveis/level_0/level_0_tapumes.csv",
    'telhados': "./niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "./niveis/level_0/level_0_telhados_fundos.csv",
    'player': "./niveis/level_0/level_0_player.csv",
    'transicao': "./niveis/level_0/level_0_transicao.csv",
    'parede_preta': "./niveis/level_0/level_0_cena2_parede_preta.csv",
    'predio_rosa': "./niveis/level_0/level_0_cena2_predio_rosa.csv",
    'predio_azul': "./niveis/level_0/level_0_cena2_predio_azul.csv",
    'chao_cena2': "./niveis/level_0/level_0_cena2_chao_cena2.csv",
    'predio_verde': "./niveis/level_0/level_0_cena2_predio_verde.csv",
    'predio_marron': "./niveis/level_0/level_0_cena2_predio_marron.csv",
    'predio_vermelho': "./niveis/level_0/level_0_cena2_predio_vermelho.csv",
    'vegetacao': "./niveis/level_0/level_0_cena2_vegetacao.csv",
    'portas_janelas_cena2': "./niveis/level_0/level_0_cena2_portas_janelas_cena2.csv",
    'props_cena2': "./niveis/level_0/level_0_cena2_props_cena2.csv",
    'constraints': "./niveis/level_0/level_0_constraints.csv",
    'enemies': "./niveis/level_0/level_0_enemies.csv",
    'node_pos': (550, 500),
    'unlock': 2,
    'node_graphics': "./img/selection/1",
}
meowolas = {
    'arbustos_casa1': "./niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "./niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "./niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "./niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "./niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "./niveis/level_0/level_0_casa_1.csv",
    'cercas': "./niveis/level_0/level_0_cercas.csv",
    'ceu': "./niveis/level_0/level_0_ceu.csv",
    'chao': "./niveis/level_0/level_0_chao.csv",
    'grades_casa2': "./niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "./niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "./niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "./niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "./niveis/level_0/level_0_portas_janelas.csv",
    'predios': "./niveis/level_0/level_0_predios.csv",
    'tapumes': "./niveis/level_0/level_0_tapumes.csv",
    'telhados': "./niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "./niveis/level_0/level_0_telhados_fundos.csv",
    'player': "./niveis/level_0/level_0_player.csv",
    'transicao': "./niveis/level_0/level_0_transicao.csv",
    'parede_preta': "./niveis/level_0/level_0_cena2_parede_preta.csv",
    'predio_rosa': "./niveis/level_0/level_0_cena2_predio_rosa.csv",
    'predio_azul': "./niveis/level_0/level_0_cena2_predio_azul.csv",
    'chao_cena2': "./niveis/level_0/level_0_cena2_chao_cena2.csv",
    'predio_verde': "./niveis/level_0/level_0_cena2_predio_verde.csv",
    'predio_marron': "./niveis/level_0/level_0_cena2_predio_marron.csv",
    'predio_vermelho': "./niveis/level_0/level_0_cena2_predio_vermelho.csv",
    'vegetacao': "./niveis/level_0/level_0_cena2_vegetacao.csv",
    'portas_janelas_cena2': "./niveis/level_0/level_0_cena2_portas_janelas_cena2.csv",
    'props_cena2': "./niveis/level_0/level_0_cena2_props_cena2.csv",
    'constraints': "./niveis/level_0/level_0_constraints.csv",
    'enemies': "./niveis/level_0/level_0_enemies.csv",
    'node_pos': (875, 500),
    'unlock': 3,
    'node_graphics': "./img/selection/2",
}
mage = {
    'arbustos_casa1': "./niveis/level_0/level_0_arbustos_casa1.csv",
    'arvore': "./niveis/level_0/level_0_arvore_casa1.csv",
    'carro': "./niveis/level_0/level_0_carro.csv",
    'casa2_fachada': "./niveis/level_0/level_0_casa2_fachada.csv",
    'casa2_fundos': "./niveis/level_0/level_0_casa2_fundos.csv",
    'casa_1': "./niveis/level_0/level_0_casa_1.csv",
    'cercas': "./niveis/level_0/level_0_cercas.csv",
    'ceu': "./niveis/level_0/level_0_ceu.csv",
    'chao': "./niveis/level_0/level_0_chao.csv",
    'grades_casa2': "./niveis/level_0/level_0_grades_casa2.csv",
    'jardim_casa1': "./niveis/level_0/level_0_jardim_casa1.csv",
    'nuvens': "./niveis/level_0/level_0_nuvens.csv",
    'pizzaria': "./niveis/level_0/level_0_pizzaria.csv",
    'portas_janelas': "./niveis/level_0/level_0_portas_janelas.csv",
    'predios': "./niveis/level_0/level_0_predios.csv",
    'tapumes': "./niveis/level_0/level_0_tapumes.csv",
    'telhados': "./niveis/level_0/level_0_telhados.csv",
    'telhados_fundos': "./niveis/level_0/level_0_telhados_fundos.csv",
    'player': "./niveis/level_0/level_0_player.csv",
    'transicao': "./niveis/level_0/level_0_transicao.csv",
    'parede_preta': "./niveis/level_0/level_0_cena2_parede_preta.csv",
    'predio_rosa': "./niveis/level_0/level_0_cena2_predio_rosa.csv",
    'predio_azul': "./niveis/level_0/level_0_cena2_predio_azul.csv",
    'chao_cena2': "./niveis/level_0/level_0_cena2_chao_cena2.csv",
    'predio_verde': "./niveis/level_0/level_0_cena2_predio_verde.csv",
    'predio_marron': "./niveis/level_0/level_0_cena2_predio_marron.csv",
    'predio_vermelho': "./niveis/level_0/level_0_cena2_predio_vermelho.csv",
    'vegetacao': "./niveis/level_0/level_0_cena2_vegetacao.csv",
    'portas_janelas_cena2': "./niveis/level_0/level_0_cena2_portas_janelas_cena2.csv",
    'props_cena2': "./niveis/level_0/level_0_cena2_props_cena2.csv",
    'constraints': "./niveis/level_0/level_0_constraints.csv",
    'enemies': "./niveis/level_0/level_0_enemies.csv",
    'node_pos': (1200, 500),
    'unlock': 4,
    'node_graphics': "./img/selection/3",
}


characters = {
    0: king,
    1: knight,
    2: meowolas,
    3: mage,
}